### ISSUE TITLE
.so files get wrong padding when zipflinger virtual entry is present

### ISSUE THREAD

**Issue by penn5** [obfusk/apksigcopier#84] opened 2023-01-31 12:36 UTC
https://github.com/obfusk/apksigcopier/blame/master/apksigcopier/__init__.py#L399 unconditionally adds this field (presumably just storing the fact that the file is aligned). I don't know why this is done, but neither the Android Gradle Plugin nor zipalign appears to insert this entry. 

My production APKs which are generated with default AGP setup do not contain this field as far as I can tell. This means that my builds aren't properly reproducible with apksigcopier. 

I've attached my three APKs for debugging: 
[debug_files.zip](https://github.com/obfusk/apksigcopier/files/10546360/debug_files.zip)

Note that I am using the vendored apksigcopier from https://gitlab.com/fdroid/fdroidserver/-/blob/282a7724ef478f645b1ffff1c25fab9848f79201/fdroidserver/apksigcopier.py which has some functions removed.

**Comment by penn5** [comment] 2023-01-31 13:29
See also: https://gitlab.com/fdroid/fdroiddata/-/issues/2816#note_1259088271

**Comment by penn5** [comment] 2023-01-31 17:02
Linked: https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/builder/src/main/java/com/android/builder/internal/packaging/ApkFlinger.kt

**Comment by penn5** [comment] 2023-01-31 17:17
Judging by https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:zipflinger/src/com/android/zipflinger/LocalFileHeader.java;l=125 there is no need for this `0xd535` field in extra.

**Comment by obfusk** [comment] 2023-01-31 20:56
> neither the Android Gradle Plugin nor zipalign appears to insert this entry.

But `apksigner`, the behaviour of which `apksigcopier` is designed to mimic exactly, does.

> My production APKs which are generated with default AGP setup do not contain this field as far as I can tell.

That is normal. The alignment field is only added *when the entry was aligned in the input APK and would no longer be aligned in the output APK*, not unconditionally.

> This means that my builds aren't properly reproducible with apksigcopier.

That statement does not follow from the previous one, see my comment above.

Please provide proof they are actually not reproducible.

**Comment by penn5** [comment] 2023-01-31 20:59
apksigcopier _is_ adding the alignment field. You can see it in the APK files I attached in the OP.

**Comment by penn5** [comment] 2023-01-31 21:00
That's on v1.1.0 as noted, not the fixes branch

**Comment by penn5** [comment] 2023-01-31 21:10
Attempting to use the `fixes` branch with `APKSIGCOPIER_SKIP_REALIGNMENT=1` I get the error `Error: APK Signing Block offset < central directory offset.` which I do not receive without skipping realignment.

**Comment by obfusk** [comment] 2023-01-31 21:12
I'll look into it as soon as I can.

**Comment by obfusk** [comment] 2023-01-31 21:13
For the record: https://android.googlesource.com/platform/tools/apksig/+/refs/heads/master/src/main/java/com/android/apksig/ApkSigner.java#77

**Comment by penn5** [comment] 2023-01-31 21:14
> For the record: https://android.googlesource.com/platform/tools/apksig/+/refs/heads/master/src/main/java/com/android/apksig/ApkSigner.java#77

Yep, I saw it too when I started looking at apksigner. Unfortunately the AGP doesn't use it... Google's motto should be "vive la fragmentation"

**Comment by obfusk** [comment] 2023-01-31 21:16
> Maybe it would be easier to just raise a bug with google asking them to delete it from apksigner

I'd prefer not having to take into account which version of `apksigner` an APK was signed with.

I'm not happy with the inconsistency between `signflinger`, `zipalign`, and `apksigner`, but please let's not also introduce inconsistencies between different versions of the same tool :)

**Comment by obfusk** [comment] 2023-01-31 21:17
I've always run `zipalign` manually on unsigned APKs if they were not properly aligned for some reason, since the 0xD935 field seems to be rare indeed. Perhaps this fixes your problem?

**Comment by obfusk** [comment] 2023-01-31 21:18
I've only seen unaligned APKs when I modified them using a tool that did not take alignment into account, like [`repro-apk`](https://github.com/obfusk/reproducible-apk-tools).

**Comment by penn5** [comment] 2023-01-31 21:19
> I've always run `zipalign` manually on unsigned APKs if they were not properly aligned for some reason, since the `0xD935` field seems to be rare indeed. Perhaps this fixes your problem?

I just tried it locally and it didn't _seem_ to help. Maybe I'm doing it wrong, but I'm still getting issues about the signing block being before the central directory. Presumably it is already aligned and it's just a bug on the fixes branch.

> I've only seen unaligned APKs when I modified them using a tool that did not take alignment into account, like [`repro-apk`](https://github.com/obfusk/reproducible-apk-tools).

I haven't done any such thing, it's just the output from AGP.

**Comment by penn5** [comment] 2023-01-31 21:22
I'd suggest adding the alignment fields (if present) of the various files in the APK to the `differences` object.

**Comment by obfusk** [comment] 2023-01-31 21:23
> Update: indeed, the output from zipalign is byte-for-byte identical to the input to zipalign. So it was already aligned.

Have you tried `zipalign -p`?

**Comment by penn5** [comment] 2023-01-31 21:24
> > Update: indeed, the output from zipalign is byte-for-byte identical to the input to zipalign. So it was already aligned.
> 
> Have you tried `zipalign -p`?

Yes, I used `zipalign -p -v 4 app-free-release-unsigned.apk output.apk`

**Comment by obfusk** [comment] 2023-02-01 02:40
The problem is almost certainly that `signflinger` adds that annoying [virtual entry](https://github.com/obfusk/apksigcopier#what-about-apks-signed-by-gradlezipflingersignflinger-instead-of-apksigner).

When `apksigcopier` adds that as well, it screws up the alignment of the `.so` files, which now need to be realigned, for which it uses the the padding scheme of `apksigner` (instead of just zeroes like `zipflinger`/`zipalign`), resulting in a mismatch in alignment padding -- but only for `.so` files, since they get aligned to 4096 bytes, not 4 like all other (non-compressed) files.

I'll look into supporting this in `apksigcopier`, but it would take a while before any updated version would be available during the F-Droid signing process.

So I would recommend signing the unsigned APK with `apksigner` instead of using a Gradle signing config; that should work correctly right now.

**Comment by penn5** [comment] 2023-02-01 09:36
> So I would recommend signing the unsigned APK with `apksigner` instead of using a Gradle signing config; that should work correctly right now.

My releases are automated, so I won't do that. I don't mind waiting a bit.

**Comment by obfusk** [comment] 2023-02-01 18:08
> My releases are automated, so I won't do that.

You can pretty easily [integrate `apksigner` with `gradle`](https://gist.github.com/obfusk/a5463fe404e22d6691f180279266b94a#file-build2-gradle); you'd have to adapt that code a bit as it's meant to *re-sign* after modifying the APK.

Another option *available right now* would be to [add the annoying virtual entry causing all this](https://gist.github.com/obfusk/ee5c27569e636df5c59c2121abb35b13) to the unsigned APK during the F-Droid build; that script requires the `fixes` branch (or the `v1.1.1` I'm hoping to release soon -- but no guarantees), but that's not a problem in the F-Droid build recipe, it's just the F-Droid signing server that won't be updated soon.

> I don't mind waiting a bit.

Up to you :)

**Comment by obfusk** [comment] 2023-02-08 07:49
Fix has been merged into `master`.

**Closed by obfusk** 2023-02-08 07:49 UTC
Labels: bug, v1.1.1
